require:
  - 'rubocop-rails'

AllCops:
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
