services:
  rails:
    build: .
    container_name: shift-eligibility
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/shift-eligibility
    ports:
      - 3000:3000
    networks:
      - seed_test_network

networks:
  seed_test_network:
    external: true
