default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: seed-db-1
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: worker_eligibility_test


production:
  <<: *default
